### ISSUE TITLE
Integrate HDF5 plugin in PIC test suite

### ISSUE THREAD

**Issue by f-schmitt** [ComputationalRadiationPhysics/picongpu#154]
I propose to integrate at least some HDF5 plugin testing into our compile/testing suite.
There could be three levels of testing and we could start with (1):
- [x] test that PIC compiles with HDF5 plugin and libSplash #456 
- [ ] test that PIC runs and produces HDF5 output files #7
- [ ] verify that output data is correct and restart is possible #7

I marked this as OpenBeta milestone since it is critical for a new user to be able to create output data.
