### ISSUE TITLE
Backports for release 0.2.0

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#1550]
The following pull requests needs to be pushed to the current release branch 0.2.0:

- [x] ~~#1545~~ splash2txt: fix compile problem
- [x] ~~#1546~~ encapsulate RNG initialization location for photons
- [x] ~~#1547~~ move RNG memory init before particle memory init 
- [x] ~~#1549~~ fix sliding window

**Comment by ax3l** [comment]
I'll also add the speed up of the RNG in ionization and the few new models to make the release's field ionization useful.

**Comment by bussmann** [comment]
Good idea!

**Comment by psychocoderHPC** [comment]
all changes are merged by @ax3l
