### ISSUE TITLE
Clean Up Runtime Moving Window Option

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#3044]
cc @sbastrakov @psychocoderHPC @n01r 

As [described](https://github.com/ComputationalRadiationPhysics/picongpu/pull/3022#issuecomment-524387095) in #3022 ten days ago, that PR was incomplete and needs a quick follow up.

Points to do that should have been updated in the original PR, because otherwise they will be forgotten in the release and are partly forgotten already:
- [x] update `docs/TBG_macros.cfg` with the new option (#3045)
- [x] update the PR description of #3022 with a "before-after" usage so one can see what needs to be changed in user input
- [x] add a note to all examples' `grid.param` files that the option therein is outdated and the new option shall be used (#3045)
- [x] fix all examples that are affected, e.g. the prime example used in our docs for all first steps, LWFA (#3045)
- [x] grep the docs and wiki for unexpected occurrences of the "moving window" technique and update usage accordingly
- [ ] bonus: consider removing `-m` and activating + setting the moving window with the new option, setting it twice in the same location causes more confusion

With #3034/#3035 and the warnings thrown, I really wonder if anyone did a runtime test before merging this ;-)

Thanks! :)

**Comment by sbastrakov** [comment]
@ax3l I've updated the before-after in that PR description. Other changes except the last one are done in #3045 . The last one: I agree this is useful to do, but would prefer separately and together with renaming of `stopWindow` so that it is more consistent: now all 3 window-related variables have different naming styles.

**Comment by ax3l** [comment]
Excellent!

yes exactly, the last step is just an independent refactoring that I am suggesting with the new parameters.

**Comment by ax3l** [comment]
Excellent!

yes exactly, the last step is just an independent refactoring that I am suggesting with the new parameters. I'll keep this PR open for reference.
