### ISSUE TITLE
remove cuSTL

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#4365]
Many parts in cuSTL are reimplementations of PMacc. 
cuSTL is providing many issue:
  - it is heavily using C-makros instead of modern C++11/C++17
  - it is currently one of the biggest issues why we can not use alpaka directly
  - most extensions/plugins using cuSTL can only be performed on GPU and **NOT** on CPU
  - cuSTL eats a lot of my working time which can not be invested into useful developments

extensions/plugins using cuSTL:
- [x] PhaseSpace plugin (possible to replace with pmacc) #4404
- [x] particle calorimeter (most likely possible to replace with pmacc) #4423
- [x] extension bremsstrahlung (hard to replace and no verification available)
- [x] extension synchrotron radiation (hard to replace and no verification available)
- [x] @finnolec upcoming shadowgraphy plugin (as I know based on PhaseSpace and therefore it should be possible to replace with pmacc) -> done https://github.com/psychocoderHPC/picongpu/tree/topic-shadowgraphy-plugin-no-cuSTL2
- [x] a few parts of the current deposition (easy to replace) #4402 #4398
- [x] randomized particle merger plugin (possible to replace but will still not runnable on CPU and no verification available)
- [x] particle merger plugin (possible to replace but will still not runnable on CPU and no verification available)
- [x] emittance plugin (possible to replace the MPI reduction part with pmacc native MPI reduce) #4366 #4426
- [x] charge conservation plugin #4424
- [x] in particle creation routines

**Comment by steindev** [comment]
Bremsstrahlung & Synchrotron #4395

**Comment by steindev** [comment]
Particle merger #4388

**Comment by steindev** [comment]
Particle creation #4363

**Comment by psychocoderHPC** [comment]
the last PR to solve this issue is in the row https://github.com/ComputationalRadiationPhysics/picongpu/pull/4434

**Comment by steindev** [comment]
Done :partying_face:
